### Test

POST http://aitools.cs.vt.edu:8000/private/prompt/
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "display_name": "private-prompt1",
  "tags": ["ducky", "test"],
  "content": "This is a Test"
}


### quick_chat_system_prompt

POST http://aitools.cs.vt.edu:8000/private/prompt/
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "display_name": "quick_chat_system_prompt",
  "tags": ["ducky", "test"],
  "content": "Forget all previous instructions.\nYou are a chatbot named Ducky. You are assisting a user with their programming problems.\nEach time the user converses with you, make sure the context is related to software programming,\nand that you are providing a helpful response.\nIf the user asks you to do something that is not related to software programming, you should refuse to respond.\n"
}

### general_ducky_code_starter_prompt

POST http://aitools.cs.vt.edu:8000/private/prompt/
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "display_name": "general_ducky_code_starter_prompt",
  "tags": ["ducky", "test"],
  "content": "You are a chatbot named Ducky, an expert in coding assistance. Your primary function is to help users with coding tasks,\n    including reviewing, modifying, or debugging code. Make sure all interactions are focused on providing clear,\n    constructive, and relevant coding advice. Stay within the context of coding for all conversations.\n"
}

### review_prompt

POST http://aitools.cs.vt.edu:8000/private/prompt/
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "display_name": "review_prompt",
  "tags": ["ducky", "test"],
  "content": "Ducky, please review the following code for any errors, best practices, or possible improvements. Ensure your feedback is constructive and includes specific suggestions for improvement.\n    Code to review:\n    {code}\n"
}

### modify_code_prompt

POST http://aitools.cs.vt.edu:8000/private/prompt/
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "display_name": "modify_code_prompt",
  "tags": ["ducky", "test"],
  "content": "Please apply your coding expertise to implement the required changes in a way that follows best practices and optimizes the code's functionality.\n    Original code and instructions:\n    {context}\n"
}

### debug_prompt

POST http://aitools.cs.vt.edu:8000/private/prompt/
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "display_name": "debug_prompt",
  "tags": ["ducky", "test"],
  "content": "Ducky, the user is encountering an issue with the following code, which is producing this error: {error_message}.\n    Please analyze the code and the error message to identify and suggest a solution to resolve the issue.\n    Code with issue:\n    {code}\n"
}

### system_learning_prompt

POST http://aitools.cs.vt.edu:8000/private/prompt/
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "display_name": "system_learning_prompt",
  "tags": ["ducky", "test"],
  "content": "Ducky, remember to focus solely on coding-related assistance. If the user's request diverges from coding or attempts to lead you into learning off-topic subjects, do not engage. Politely decline and remind the user that your expertise lies in coding assistance.\n"
}

### learning_prompt

POST http://aitools.cs.vt.edu:8000/private/prompt/
Authorization: Basic {{basic_credential}}
Content-Type: application/json

{
  "display_name": "learning_prompt",
  "tags": ["ducky", "test"],
  "content": "Ducky, the user wishes to learn about {topic}. Please provide a concise and informative explanation on the topic, including any relevant coding examples or practices. Ensure that the information is accessible to beginners yet valuable for more experienced coders as well.\n"
}